In [5]:
file_name="/Users/mariasuriel/Desktop/BSE/T1/Computing for Data Science/hw4/hw4/sample_diabetes_mellitus_data.csv"

In [10]:

# a. Load the data
import pandas as pd

def data_loader(file_name: str) -> pd.DataFrame:
    data = pd.read_csv(file_name)
    #print(f"Data loaded successfully. Shape: {data.shape}")
    return data

In [11]:
data_loader(file_name)

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,...,0,14.1,0,0,0,0,0,0,0,1
1,1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,...,1,12.7,0,0,0,0,0,0,0,1
2,2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
3,3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,...,1,8.0,0,0,0,0,0,0,0,0
4,4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,167042,140,NaN,51.952814,0,Caucasian,F,137.20,Floor,...,0,7.0,0,0,0,0,0,0,0,0
9996,9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,...,0,9.5,0,0,0,0,0,0,0,0
9997,9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
9998,9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,...,0,6.4,0,0,0,0,0,0,0,0
9999,9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,...,1,NaN,0,0,0,0,0,0,0,0

In [13]:
def data_split(file_name):
    data=data_loader(file_name)
    from sklearn.model_selection import train_test_split
    train, test = train_test_split(data, test_size=0.2, random_state=42)
    return train,test

In [ ]:
train,test=data_split(file_name)

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
6252,6252,275141,81,66.0,34.852863,0,Caucasian,M,180.30,Emergency Department,...,1,7.6,0,0,0,0,0,0,0,1
4684,4684,269942,118,NaN,18.593750,0,Caucasian,F,160.00,NaN,...,0,6.9,0,0,0,0,0,0,0,0
1731,1731,183562,118,83.0,28.215375,0,Caucasian,F,154.90,Other Hospital,...,1,19.6,0,0,0,0,0,0,0,0
4742,4742,244929,118,64.0,21.575502,1,Caucasian,F,170.20,Emergency Department,...,0,10.0,0,0,0,1,0,0,0,0
4521,4521,193781,118,21.0,34.560280,1,African American,F,162.00,Operating Room,...,1,18.0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,6412,183270,118,80.0,20.087932,0,Caucasian,F,162.60,Emergency Department,...,1,8.5,0,0,0,0,0,0,0,0
8285,8285,254168,89,80.0,22.326705,0,Caucasian,F,162.56,Direct Admit,...,0,6.4,0,0,0,0,0,0,0,0
7853,7853,269140,81,59.0,NaN,0,Caucasian,M,160.00,Emergency Department,...,0,16.8,0,0,0,0,0,0,0,0
1095,1095,201230,83,79.0,25.311715,1,Caucasian,M,167.60,Operating Room,...,0,14.9,0,0,0,0,0,0,0,0
6929,6929,240583,77,72.0,NaN,1,Caucasian,M,182.90,Operating Room,...,1,19.9,0,0,0,0,0,0,0,0

In [19]:
train

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
9254,9254,185898,137,88.0,28.713767,0,Caucasian,F,157.48,Emergency Department,...,0,11.5,0,0,0,0,1,0,0,1
1561,1561,179718,83,69.0,NaN,0,Caucasian,F,152.40,Floor,...,0,8.9,0,0,0,0,0,0,0,1
1670,1670,204365,118,61.0,NaN,0,Caucasian,M,188.00,NaN,...,0,10.2,0,0,0,0,0,0,0,0
6087,6087,167361,118,36.0,33.861606,1,African American,F,165.10,Operating Room,...,1,30.9,0,0,0,0,0,0,0,0
6669,6669,213013,83,49.0,22.693954,1,Caucasian,F,162.60,Operating Room,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,5734,232888,118,86.0,NaN,0,Caucasian,F,160.00,Emergency Department,...,0,31.4,0,0,0,0,0,0,0,1
5191,5191,210825,118,68.0,32.549816,1,African American,M,176.50,Operating Room,...,0,12.6,0,0,0,0,0,0,0,0
5390,5390,240686,151,54.0,24.509470,1,Caucasian,M,162.60,NaN,...,0,10.6,0,0,0,0,0,0,0,0
860,860,231954,33,87.0,28.566361,0,Caucasian,M,172.70,Emergency Department,...,1,20.4,0,0,0,0,0,0,0,0
7270,7270,185737,118,60.0,19.400691,1,Caucasian,M,170.20,Operating Room,...,0,16.6,0,0,0,0,0,0,0,0

In [20]:
test

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
6252,6252,275141,81,66.0,34.852863,0,Caucasian,M,180.30,Emergency Department,...,1,7.6,0,0,0,0,0,0,0,1
4684,4684,269942,118,NaN,18.593750,0,Caucasian,F,160.00,NaN,...,0,6.9,0,0,0,0,0,0,0,0
1731,1731,183562,118,83.0,28.215375,0,Caucasian,F,154.90,Other Hospital,...,1,19.6,0,0,0,0,0,0,0,0
4742,4742,244929,118,64.0,21.575502,1,Caucasian,F,170.20,Emergency Department,...,0,10.0,0,0,0,1,0,0,0,0
4521,4521,193781,118,21.0,34.560280,1,African American,F,162.00,Operating Room,...,1,18.0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,6412,183270,118,80.0,20.087932,0,Caucasian,F,162.60,Emergency Department,...,1,8.5,0,0,0,0,0,0,0,0
8285,8285,254168,89,80.0,22.326705,0,Caucasian,F,162.56,Direct Admit,...,0,6.4,0,0,0,0,0,0,0,0
7853,7853,269140,81,59.0,NaN,0,Caucasian,M,160.00,Emergency Department,...,0,16.8,0,0,0,0,0,0,0,0
1095,1095,201230,83,79.0,25.311715,1,Caucasian,M,167.60,Operating Room,...,0,14.9,0,0,0,0,0,0,0,0
6929,6929,240583,77,72.0,NaN,1,Caucasian,M,182.90,Operating Room,...,1,19.9,0,0,0,0,0,0,0,0

In [26]:
def data_remove_nans(file_name):
    train,test=data_split(file_name)
    train = train.dropna(subset=['age', 'gender', 'ethnicity'])
    test = test.dropna(subset=['age', 'gender', 'ethnicity'])
    return train,test

In [27]:
train,test=data_remove_nans(file_name)

In [28]:
train

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
9254,9254,185898,137,88.0,28.713767,0,Caucasian,F,157.48,Emergency Department,...,0,11.5,0,0,0,0,1,0,0,1
1561,1561,179718,83,69.0,NaN,0,Caucasian,F,152.40,Floor,...,0,8.9,0,0,0,0,0,0,0,1
1670,1670,204365,118,61.0,NaN,0,Caucasian,M,188.00,NaN,...,0,10.2,0,0,0,0,0,0,0,0
6087,6087,167361,118,36.0,33.861606,1,African American,F,165.10,Operating Room,...,1,30.9,0,0,0,0,0,0,0,0
6669,6669,213013,83,49.0,22.693954,1,Caucasian,F,162.60,Operating Room,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,5734,232888,118,86.0,NaN,0,Caucasian,F,160.00,Emergency Department,...,0,31.4,0,0,0,0,0,0,0,1
5191,5191,210825,118,68.0,32.549816,1,African American,M,176.50,Operating Room,...,0,12.6,0,0,0,0,0,0,0,0
5390,5390,240686,151,54.0,24.509470,1,Caucasian,M,162.60,NaN,...,0,10.6,0,0,0,0,0,0,0,0
860,860,231954,33,87.0,28.566361,0,Caucasian,M,172.70,Emergency Department,...,1,20.4,0,0,0,0,0,0,0,0
7270,7270,185737,118,60.0,19.400691,1,Caucasian,M,170.20,Operating Room,...,0,16.6,0,0,0,0,0,0,0,0

In [29]:
test

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
6252,6252,275141,81,66.0,34.852863,0,Caucasian,M,180.30,Emergency Department,...,1,7.6,0,0,0,0,0,0,0,1
1731,1731,183562,118,83.0,28.215375,0,Caucasian,F,154.90,Other Hospital,...,1,19.6,0,0,0,0,0,0,0,0
4742,4742,244929,118,64.0,21.575502,1,Caucasian,F,170.20,Emergency Department,...,0,10.0,0,0,0,1,0,0,0,0
4521,4521,193781,118,21.0,34.560280,1,African American,F,162.00,Operating Room,...,1,18.0,0,0,0,0,0,0,0,0
6340,6340,178229,118,66.0,40.374334,0,Asian,F,137.20,NaN,...,0,5.2,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,6412,183270,118,80.0,20.087932,0,Caucasian,F,162.60,Emergency Department,...,1,8.5,0,0,0,0,0,0,0,0
8285,8285,254168,89,80.0,22.326705,0,Caucasian,F,162.56,Direct Admit,...,0,6.4,0,0,0,0,0,0,0,0
7853,7853,269140,81,59.0,NaN,0,Caucasian,M,160.00,Emergency Department,...,0,16.8,0,0,0,0,0,0,0,0
1095,1095,201230,83,79.0,25.311715,1,Caucasian,M,167.60,Operating Room,...,0,14.9,0,0,0,0,0,0,0,0
6929,6929,240583,77,72.0,NaN,1,Caucasian,M,182.90,Operating Room,...,1,19.9,0,0,0,0,0,0,0,0

In [30]:
def data_fill_nans(file_name):
    train,test=data_remove_nans(file_name)
    train['height'] = train['height'].fillna(train['height'].mean())
    train['weight'] = train['weight'].fillna(train['weight'].mean())
    test['height'] = test['height'].fillna(test['height'].mean())
    test['weight'] = test['weight'].fillna(test['weight'].mean())
    return train,test

In [31]:
train,test=data_fill_nans(file_name)

In [33]:
train.isna().sum()

Unnamed: 0                        0
encounter_id                      0
hospital_id                       0
age                               0
bmi                            1275
elective_surgery                  0
ethnicity                         0
gender                            0
height                            0
hospital_admit_source           693
icu_admit_source                 17
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                            0
albumin_apache                 4834
apache_2_diagnosis              143
apache_3j_diagnosis              40
apache_post_operative             0
arf_apache                        0
bilirubin_apache               4941
bun_apache                     1895
creatinine_apache              1787
fio2_apache                    5264
gcs_eyes_apache                  53
gcs_motor_apache                 53
gcs_unable_apache                49
gcs_verbal_apache                53
glucose_apache                  799
heart_rate_apache                 0
hematocrit_apache              1500
intubated_apache                  0
map_apache                        9
paco2_apache                   5264
paco2_for_ph_apache            5264
pao2_apache                    5264
ph_apache                      5264
resprate_apache                  26
sodium_apache                  1853
temp_apache                      66
urineoutput_apache             6394
ventilated_apache                 0
wbc_apache                     1646
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

In [34]:
test.isna().sum()

Unnamed: 0                        0
encounter_id                      0
hospital_id                       0
age                               0
bmi                             347
elective_surgery                  0
ethnicity                         0
gender                            0
height                            0
hospital_admit_source           157
icu_admit_source                  4
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                            0
albumin_apache                 1212
apache_2_diagnosis               34
apache_3j_diagnosis               9
apache_post_operative             0
arf_apache                        0
bilirubin_apache               1229
bun_apache                      477
creatinine_apache               460
fio2_apache                    1319
gcs_eyes_apache                  12
gcs_motor_apache                 12
gcs_unable_apache                12
gcs_verbal_apache                12
glucose_apache                  209
heart_rate_apache                 1
hematocrit_apache               379
intubated_apache                  0
map_apache                        3
paco2_apache                   1319
paco2_for_ph_apache            1319
pao2_apache                    1319
ph_apache                      1319
resprate_apache                   7
sodium_apache                   468
temp_apache                      19
urineoutput_apache             1587
ventilated_apache                 0
wbc_apache                      408
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

In [35]:
#e.Generate dummies for ethnicity column (One hot encoding).
def data_encoding(file_name):
    train,test=data_fill_nans(file_name)
    train = pd.get_dummies(train, columns=['ethnicity'], drop_first=True)
    test = pd.get_dummies(test, columns=['ethnicity'], drop_first=True)
    return train,test

In [36]:
train,test=data_encoding(file_name)

In [37]:
train

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,gender,height,hospital_admit_source,icu_admit_source,...,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Native American,ethnicity_Other/Unknown
9254,9254,185898,137,88.0,28.713767,0,F,157.48,Emergency Department,Accident & Emergency,...,0,1,0,0,1,False,True,False,False,False
1561,1561,179718,83,69.0,NaN,0,F,152.40,Floor,Floor,...,0,0,0,0,1,False,True,False,False,False
1670,1670,204365,118,61.0,NaN,0,M,188.00,NaN,Accident & Emergency,...,0,0,0,0,0,False,True,False,False,False
6087,6087,167361,118,36.0,33.861606,1,F,165.10,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,False,False,False,False,False
6669,6669,213013,83,49.0,22.693954,1,F,162.60,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,5734,232888,118,86.0,NaN,0,F,160.00,Emergency Department,Accident & Emergency,...,0,0,0,0,1,False,True,False,False,False
5191,5191,210825,118,68.0,32.549816,1,M,176.50,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,False,False,False,False,False
5390,5390,240686,151,54.0,24.509470,1,M,162.60,NaN,Operating Room / Recovery,...,0,0,0,0,0,False,True,False,False,False
860,860,231954,33,87.0,28.566361,0,M,172.70,Emergency Department,Accident & Emergency,...,0,0,0,0,0,False,True,False,False,False
7270,7270,185737,118,60.0,19.400691,1,M,170.20,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,False,True,False,False,False

In [38]:
test

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,gender,height,hospital_admit_source,icu_admit_source,...,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Native American,ethnicity_Other/Unknown
6252,6252,275141,81,66.0,34.852863,0,M,180.30,Emergency Department,Accident & Emergency,...,0,0,0,0,1,False,True,False,False,False
1731,1731,183562,118,83.0,28.215375,0,F,154.90,Other Hospital,Other Hospital,...,0,0,0,0,0,False,True,False,False,False
4742,4742,244929,118,64.0,21.575502,1,F,170.20,Emergency Department,Operating Room / Recovery,...,1,0,0,0,0,False,True,False,False,False
4521,4521,193781,118,21.0,34.560280,1,F,162.00,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,False,False,False,False,False
6340,6340,178229,118,66.0,40.374334,0,F,137.20,NaN,Accident & Emergency,...,0,0,0,0,1,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,6412,183270,118,80.0,20.087932,0,F,162.60,Emergency Department,Accident & Emergency,...,0,0,0,0,0,False,True,False,False,False
8285,8285,254168,89,80.0,22.326705,0,F,162.56,Direct Admit,Accident & Emergency,...,0,0,0,0,0,False,True,False,False,False
7853,7853,269140,81,59.0,NaN,0,M,160.00,Emergency Department,Accident & Emergency,...,0,0,0,0,0,False,True,False,False,False
1095,1095,201230,83,79.0,25.311715,1,M,167.60,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,False,True,False,False,False
6929,6929,240583,77,72.0,NaN,1,M,182.90,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,False,True,False,False,False